---
- name: Ensure MySQL packages are installed.
  yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: suse_mysql_install_packages
